version: '3'
services:
  gateway:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - wplocaldocker
  mysql:
    image: mysql:5
    volumes:
      - "mysqlData:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - wplocaldocker
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILCATCHER_PORT: 1025
    networks:
      - wplocaldocker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8092:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - wplocaldocker
networks:
  wplocaldocker:
    external:
      name: "wplocaldocker"
volumes:
  mysqlData:
