blank_issues_enabled: false
contact_links:
    - name: Looking for documentation?
      url: https://10up.github.io/wp-local-docker-docs/
      about: If you're looking for information on installation, global commands, environments, WP Snapshots, and related tools then check out the WP Local Docker documentation site.
